spring:
  application:
    name: api

logging:
  level:
    root: INFO
    com.example.mvc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: loggers,env,health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always
      group:
        liveness:
          include: ping
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true

  metrics:
    tags:
      service: ${spring.application.name}
      env: ${app.env}
      version: ${app.version}

  info:
    env:
      enabled: true